in: "data/diabetes.csv"

out:
  "log"

target: Diabetic

save_model: True

models:
- estimator: DecisionTreeClassifier
  module: sklearn.tree
  hyperparams: 
    max_depth: 
      - 5 

- estimator: RandomForestClassifier
  module: sklearn.ensemble
  hyperparams:
    max_depth:
      - 5

target: Diabetic
features:
  numeric:
    - Pregnancies
    - PlasmaGlucose
    - DiastolicBloodPressure
    - TricepsThickness
    - SerumInsulin
    - BMI
    - DiabetesPedigree
  drop: PatientID

  