in: "../data/diabetes.csv"

out:
  "../log"

target: Diabetic

models:
- estimator: DecisionTreeClassifier
  module: sklearn.tree
  hyperparams: 
    max_depth: 
      - 5 
      - 10
- estimator: RandomForestClassifier
  module: sklearn.ensemble
  hyperparams:
    max_depth:
      - 6 
      - 10
      - 11




  