paths:
  data: "../data"
  log: "../logs"

files:
  input_file: diabetes.csv
  output_file: outlog.dat

models:
- estimator: DecisionTreeClassifier
  module: sklearn.tree
  hyperparams: 
    max_depth: 
      - 5 
      - 10
- estimator: RandomForestClassifier
  module: sklearn.ensemble
  hyperparams:
    max_depth:
      - 6 
      - 10




  