name: CI/CD Pipeline
on:
  workflow_dispatch:
  push: 
    branches:
      - main
    paths:
      - log/clfmodel.pkl
jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Check out repo
        uses: actions/checkout@v3
  
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: jcsimmons/ml-app
  
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ml-app:latest

  render:
    needs: docker
    name: Redeploy Render API
    runs-on: ubuntu-latest
    steps:

      - name: deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"



  api-check:
    name: Call API
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: wait
        run: sleep 180s
        
      - name: call-api
        id: call
        run: |
          response=$(curl -H "Content-Type: application/json" \
          --data @test.json -s -w "%{http_code}" \
          https://ml-api-imwi.onrender.com) 
          status_code="$(echo "$response" | tail -n 1)"
          echo $status_code
          echo "status_code=$status_code" >> $GITHUB_OUTPUT

      - name: check
        if: ${{ steps.call.outputs.status }}  != 200
        run: |
          echo "Failed with code ${{ steps.call.outputs.status_code}} "

    
